### ISSUE TITLE
calculation seems 'off'

### ISSUE THREAD

**Issue by franckl** [Turfjs/turf-point-on-line#1]
Hi 

Please have a look at http://jsfiddle.net/franckl/775hbwta/
It seems to me that the "snapped" point returned by point-on-line is slightly off mark.

Intuitively the closest point should be at the intersection with the red line on the screenshot below (the LineString is not a straight line but close to, so the intersection should be at ~90degrees)
![image](https://cloud.githubusercontent.com/assets/3875803/9583539/8d415466-4fd1-11e5-9e7e-d9cf0e8fe06c.png)

Could it be that the closest distance is in km/miles instead of the closest distance on a "flat" map ?
If so would it be possible to add an option to calculate the distance based on a x/y plane ?

**Comment by aurelien-defossez** [comment]
The problem comes from the intersection algorithm, it does not take into account the earth curvature.

And turf is actually using a 1000 miles segment to find the intersection with the line, which is hugely impacted by the earth curvature.

I made a fix you can find in the Pull Request #4. This fixes notably your bug, because I replaced this "1000 miles" by a distance which is closer to what the user is looking for.

But the problem will still be there for large distance, because I didn't modify the intersection algorithm.
