### ISSUE TITLE
If the point is exactly on the line, it gets snapped at a vertex of this line

### ISSUE THREAD

**Issue by aurelien-defossez** [Turfjs/turf-point-on-line#3]
If a point is exactly on the line, both the intersection tests will fail, because we try to find the intersection between a line starting on another one twice.

Therefore, intersectPt will be undefined and the point will be snapped to either start or stop.

**Comment by PieceMaker** [comment]
I too have run into this issue, but depending on your linestring, the intersection point may be another part of the line rather than start or stop. For example, use the following line and point definition:

``` javascript
var line = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "LineString",
    "coordinates": [
                        [0.0,0.0],
                        [1.0,0.0],
                        [1.0,3.0],
                        [2.0,3.0],
                        [2.0,0.0],
                        [3.0,0.0],
                        [3.0,4.0],
                        [0.0,4.0],
                        [0.0,0.0]
                ]
  }
};
var pt = {
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point",
    "coordinates": [0,1]
  }
};
```

The point `(0,1)` is on the linestring but when you run the function with these inputs, you get `(1,1)` as your result, which is neither the start or stop point, nor is it even a vertex of the linestring.
